export const PROPERTY_PHOTO_FIELD_NAME = 'photos';
export const MAX_PROPERTY_PHOTOS = 4;
export const MAX_PROPERTY_PHOTO_BYTES = 5 * 1024 * 1024;
export const MAX_PROPERTY_PHOTO_PIXELS = 40_000_000;
export const MAX_PROPERTY_PHOTO_DIMENSION = 12_000;
export const MAX_PROPERTY_PHOTO_ALT_TEXT = 200;

export const PROPERTY_PHOTO_STORAGE = Symbol('PROPERTY_PHOTO_STORAGE');
